07-Jul-2024 22:32:59.830 INFORMACIÓN [http-nio-8080-exec-23] org.apache.catalina.core.ApplicationContext.log inicializando el request!
07-Jul-2024 22:33:00.249 GRAVE [http-nio-8080-exec-23] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() para servlet [default] lanzó excepción
	java.lang.RuntimeException: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
		at org.aguzman.apiservlet.webapp.headers.filters.ConexionFilter.doFilter(ConexionFilter.java:33)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
		at org.aguzman.apiservlet.webapp.headers.util.ConexionBaseDatos.getConnection(ConexionBaseDatos.java:14)
		at org.aguzman.apiservlet.webapp.headers.filters.ConexionFilter.doFilter(ConexionFilter.java:18)
		... 19 more
07-Jul-2024 22:33:00.249 INFORMACIÓN [http-nio-8080-exec-23] org.apache.catalina.core.ApplicationContext.log destruyendo el request!
07-Jul-2024 22:41:44.511 INFORMACIÓN [http-nio-8080-exec-26] org.apache.catalina.core.ApplicationContext.log destruyendo la aplicacion!
07-Jul-2024 22:41:45.760 INFORMACIÓN [http-nio-8080-exec-26] org.apache.catalina.core.ApplicationContext.log inicializando la aplicacion!
07-Jul-2024 22:41:48.689 INFORMACIÓN [http-nio-8080-exec-27] org.apache.catalina.core.ApplicationContext.log inicializando el request!
07-Jul-2024 22:41:48.733 GRAVE [http-nio-8080-exec-27] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() para servlet [default] lanzó excepción
	java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Unknown database 'java_curso'
		at org.aguzman.apiservlet.webapp.headers.filters.ConexionFilter.doFilter(ConexionFilter.java:33)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: java.sql.SQLSyntaxErrorException: Unknown database 'java_curso'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
		at org.aguzman.apiservlet.webapp.headers.util.ConexionBaseDatos.getConnection(ConexionBaseDatos.java:15)
		at org.aguzman.apiservlet.webapp.headers.filters.ConexionFilter.doFilter(ConexionFilter.java:18)
		... 19 more
07-Jul-2024 22:41:48.734 INFORMACIÓN [http-nio-8080-exec-27] org.apache.catalina.core.ApplicationContext.log destruyendo el request!
07-Jul-2024 22:41:58.399 INFORMACIÓN [http-nio-8080-exec-24] org.apache.catalina.core.ApplicationContext.log inicializando el request!
07-Jul-2024 22:41:58.419 GRAVE [http-nio-8080-exec-24] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() para servlet [default] lanzó excepción
	java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Unknown database 'java_curso'
		at org.aguzman.apiservlet.webapp.headers.filters.ConexionFilter.doFilter(ConexionFilter.java:33)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: java.sql.SQLSyntaxErrorException: Unknown database 'java_curso'
		at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
		at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
		at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828)
		at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:448)
		at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:241)
		at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
		at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
		at org.aguzman.apiservlet.webapp.headers.util.ConexionBaseDatos.getConnection(ConexionBaseDatos.java:15)
		at org.aguzman.apiservlet.webapp.headers.filters.ConexionFilter.doFilter(ConexionFilter.java:18)
		... 19 more
07-Jul-2024 22:41:58.419 INFORMACIÓN [http-nio-8080-exec-24] org.apache.catalina.core.ApplicationContext.log destruyendo el request!
07-Jul-2024 23:24:47.562 INFORMACIÓN [Thread-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
07-Jul-2024 23:24:47.563 INFORMACIÓN [Thread-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()
07-Jul-2024 23:24:47.578 INFORMACIÓN [Thread-1] org.apache.catalina.core.ApplicationContext.log destruyendo la aplicacion!
